# Configuration for pre-commit
# https://pre-commit.com/#advanced

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        name: black
        stages: [commit]
        types: [python]
#        args: ["--check"]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        stages: [commit]
        language: system
        entry: pipenv run pylint --suggestion-mode=y
        types: [python]
